app/routes.py
from flask import Blueprint, render_template, redirect, url_for, flash, jsonify, request
from flask_login import login_user, login_required, logout_user, current_user

from app import db, bcrypt
from app.forms import LoginForm, RegisterForm, PostForm, CommentForm, EditPostForm
from app.models import User, Post, Comment, likes

main = Blueprint('main', __name__)

"""
This module, routes.py, defines all user-facing URL endpoints for the Flask web application. 
The routes are organized by functionality. Key Flask extensions used include Flask-Login for 
session management, WTForms for form processing, and Bcrypt for password hashing.
"""


@main.route('/')
def home():
    return render_template('home.html', template='home')


# Logs in a user based on data extracted from a login WTForm
@main.route('/login', methods=['GET', 'POST'])
def login():
    # Using the WTForm for login
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user:
            if bcrypt.check_password_hash(user.password, form.password.data):

                # Log in the user
                login_user(user)
                return redirect(url_for('main.view_all'))
            else:
                flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', template='login', form=form)


@main.route('/logout', methods=['GET', 'POST'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.login'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    # Using the WTForm for registering
    form = RegisterForm()
    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user:
            flash('Email already registered. Please log in or use a different email.', 'warning')
            return redirect(url_for('main.register'))

        # Hashing the password with bcrypt
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')

        # Adding the new user to the database
        new_user = User(
            email=form.email.data,
            password=hashed_password,
            first_name=form.first_name.data,
            family_name=form.family_name.data
        )
        db.session.add(new_user)
        db.session.commit()

        flash('Registration successful. Please log in.', 'success')
        return redirect(url_for('main.login'))
    return render_template('register.html', template='register', form=form)


# Helper function to query posts by sorting option
def sort_post(sort, quantity):
    """
    :param sort: 'likes', otherwise sorting by date.
    :param quantity: the number of posts to be returned.
    :return: a list of post objects.
    """
    if sort == 'likes':
        posts = Post.query \
            .outerjoin(likes, Post.id == likes.c.post_id) \
            .group_by(Post.id) \
            .order_by(db.func.count(likes.c.post_id).desc(), Post.date_posted.desc()) \
            .limit(quantity).all()
    else:  # Default sort by date
        posts = Post.query.order_by(Post.date_posted.desc()).limit(quantity).all()
    return posts


# This is the "view_all" function, but I named the endpoint "Dashboard".
@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def view_all():
    # Initiating the WTForm for posts
    form = PostForm()

    # Getting the top 10 posts by current sorting option
    sort = request.args.get('sort', 'date')
    posts = sort_post(sort, 10)

    # Check which posts the current user has liked
    liked_post_ids = set()
    if current_user.is_authenticated:
        liked_post_ids = {post.id for post in current_user.liked_posts}

    return render_template('dashboard.html', template='dashboard', posts=posts, sort=sort, form=form,
                           liked_post_ids=liked_post_ids)


# Endpoint for creating new posts
@main.route('/add_post', methods=['POST'])
@login_required
def add_post():
    form = PostForm()

    # Create a new post using data from the WTForm
    new_post = Post(title=form.title.data, content=form.content.data, author=current_user)
    db.session.add(new_post)
    db.session.commit()

    flash('Your post has been created!', 'success')
    return redirect(url_for('main.view_all'))


# View function for displaying the view_post page for any given post
@main.route('/post/<int:post_id>', methods=['GET', 'POST'])
@login_required
def view_post(post_id):
    post = Post.query.get_or_404(post_id)
    comments = Comment.query.filter_by(post_id=post.id).all()
    comment_form = CommentForm()
    edit_post_form = EditPostForm()

    # Check which posts the current user has liked
    liked_post_ids = set()
    if current_user.is_authenticated:
        liked_post_ids = {post.id for post in current_user.liked_posts}

    return render_template('view_post.html', template='view_post', post=post, comments=comments,
                           comment_form=comment_form, edit_post_form=edit_post_form, liked_post_ids=liked_post_ids)


# Endpoint for liking posts
@main.route('/like_post/<int:post_id>', methods=['POST'])
@login_required
def like_post(post_id):
    post = Post.query.get_or_404(post_id)
    if current_user in post.likers:
        post.likers.remove(current_user)
        db.session.commit()
        return jsonify({'result': 'unliked', 'likes_count': len(post.likers)})
    else:
        post.likers.append(current_user)
        db.session.commit()
        return jsonify({'result': 'liked', 'likes_count': len(post.likers)})


# Endpoint for adding comments to a given post
@main.route('/add_comment/<int:post_id>', methods=['POST'])
@login_required
def add_comment(post_id):
    post = Post.query.get_or_404(post_id)
    comment_form = CommentForm()

    if comment_form.validate_on_submit():
        comment = Comment(content=comment_form.content.data, post_id=post.id, author=current_user)
        db.session.add(comment)
        db.session.commit()
    else:
        flash('Error adding comment.', 'error')

    return redirect(url_for('main.view_post', post_id=post.id))


# Deletes a given comment if its author is the current user
@main.route('/delete_comment/<int:comment_id>', methods=['DELETE'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)

    # Check if the current user is authorized to delete the comment
    if current_user != comment.author:
        return jsonify({'message': 'Unauthorized'}), 403

    db.session.delete(comment)
    db.session.commit()
    return jsonify({'message': 'Comment deleted'})


# Endpoint for editing a comment
@main.route('/edit_comment/<int:comment_id>', methods=['POST'])
@login_required
def edit_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)

    # Check if the current user is authorized to edit the comment
    if current_user != comment.author:
        return jsonify({'message': 'Unauthorized'}), 403

    data = request.json
    comment.content = data['content']
    db.session.commit()
    return jsonify({'message': 'Comment updated'})


# Endpoint for updating a post
@main.route('/update_post/<int:post_id>', methods=['POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    # Check if the current user is authorized to edit the post
    if current_user != post.author:
        return jsonify({'message': 'Unauthorized'}), 403

    post.title = request.form.get('title')
    post.content = request.form.get('content')
    db.session.commit()
    flash('Post updated', 'success')
    return redirect(url_for('main.view_all'))


@main.route('/delete_post/<int:post_id>', methods=['DELETE'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)

    # Check if the current user is authorized to edit the post
    if current_user != post.author:
        return jsonify({'message': 'Unauthorized'}), 403

    db.session.delete(post)
    db.session.commit()
    flash('Post deleted', 'success')
    return jsonify({'message': 'Post deleted'})

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <!-- Default Bootstrap CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.min.css') }}">
  <!-- Bootstrap JS Bundle with Popper -->
  <script src="{{ url_for('static', filename='js/bootstrap.bundle.min.js') }}"></script>

  <!-- Font Awesome -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/all.min.css') }}">

  <!-- CTK general CSS -->
  <link rel="stylesheet" href="{{ url_for('static', filename='css/ctk-general.css') }}">

  <!-- Page CSS link based on 'template' variable -->
  {% if template %}
  <link rel="stylesheet" href="{{ url_for('static', filename=template + '/' + template + '.css') }}">
  {% endif %}

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <title>ctkonnekt</title>

</head>

<body>

  {% include 'partials/navbar.html' %}

  <div class="container pt-5 d-flex justify-content-center align-items-center">

    <div class="col mb-5">

      <!-- Display flash messages and form errors -->
      {% with messages = get_flashed_messages(with_categories=true) %}
      {% if messages %}
      {% for category, message in messages %}
      <div class="alert alert-{{ category }}">
        {{ message }}
      </div>
      {% endfor %}
      {% endif %}
      {% endwith %}

      <!-- Dynamic Page Content -->
      {% block content %}{% endblock %}

    </div>

  </div>

  <!-- Page script link based on 'template' variable -->
  {% if template %}
  <script src="{{ url_for('static', filename=template + '/' + template + '.js') }}"></script>
  {% endif %}

  <!-- Global scripts -->
  <script src="{{ url_for('static', filename='js/global.js') }}"></script>

  <!-- Lottie animations script -->
  <script src="{{ url_for('static', filename='js/lottie.min.js') }}"></script>

</body>

</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

<h5 class="d-flex justify-content-center pb-3">What's on your mind, {{current_user.first_name}}?</h5>

<!-- Create post button -->
<div class="d-flex justify-content-center align-items-center">
    <!-- Button to trigger modal -->
    <button class="btn btn-outline-primary btn-lg w-75" type="button" data-bs-toggle="modal" data-bs-target="#createPostModal">
        New Post
        <i class="fa-solid fa-pen-to-square"></i>
    </button>
</div>

<!-- Create post modal -->
<div class="modal fade" id="createPostModal" tabindex="-1" aria-labelledby="createPostModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="createPostModalLabel">Create Post</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <!-- Create Post Form -->
                <form action="{{ url_for('main.add_post') }}" method="post">
                    {{ form.hidden_tag() }}
                    <div class="mb-3">
                        {{ form.title.label(class="form-label") }}
                        {{ form.title(class="form-control") }}
                    </div>
                    <div class="mb-3">
                        {{ form.content.label(class="form-label") }}
                        {{ form.content(class="form-control") }}
                    </div>
                    <button type="submit" class="btn btn-primary">Create Post</button>
                </form>
            </div>
        </div>
    </div>
</div>

<hr>

<!-- All posts section -->

<h5>Top Posts</h5>
<div>
    <a href="{{ url_for('main.view_all', sort='date') }}">Sort by Date</a> |
    <a href="{{ url_for('main.view_all', sort='likes') }}">Sort by Likes</a>
</div>

<hr>

<div class="post-list">
    {% for post in posts %}
    <div class="post" data-post-id="{{ post.id }}">
        <!-- Post standard layout -->
        {% include 'partials/post_content_layout.html' %}
        <br>
        <small>{{ post.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>
    </div>
    <hr>

    {% else %}
    <p>No posts found.</p>
    {% endfor %}
</div>

{% endblock %}

app/templates/home.html
<!-- home.html -->
{% extends 'base.html' %}

{% block content %}

<!-- Animation -->
<div class="container pt-5 d-flex justify-content-center align-items-center animation-container">
    <div class="hello-animation-container" style="width: 50%; filter: grayscale(1); margin-top: -150px">
        <div id="lottie-hello-animation"></div>
    </div>
</div>

<div style="margin-top: -80px">
    <h4 class="d-flex justify-content-center">
        welcome to ctkonnekt
    </h4>
</div>

{% if current_user.is_authenticated %}
<div class="d-flex justify-content-center pt-2">
    <a class="px-2" href="{{ url_for('main.view_all') }}" style="text-decoration: none;">
        <button type="button" class="btn btn-outline-primary btn-lg">
            View Posts
        </button>
    </a>
</div>
{% else %}
<!-- Login and register buttons -->
<div class="d-flex justify-content-center pt-2">
    <a class="px-2" href="{{ url_for('main.register') }}" style="text-decoration: none;">
        <button type="button" class="btn btn-outline-primary btn-lg">
            Register
        </button>
    </a>

    <a class="px-2" href="{{ url_for('main.login') }}" style="text-decoration: none;">
        <button type="button" class="btn btn-outline-primary btn-lg">
            Login
        </button>
    </a>
</div>
{% endif %}

<h4 class="d-flex justify-content-center pt-5 mt-3">
    My attempt at the IT-case for CTK
</h4>
<p class="d-flex justify-content-center pt-2">
    This web application is built using Python Flask, which I have utilized for both server-side programming and rendering the frontend. The simple structure of this application allowed me to finish this project in the least amount of time, which was necessary given the short deadline of one week. <br> <hr>
    Try registering a new account, or, if you generated the default sample data, you can log in using for example "olvik@chalmers.se", "123456789".
</p>

{% endblock %}

app/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}

{% block content %}

<h2>Log in</h2>
  <p>Log in using your ctkonnekt account below.</p>

  <form method="POST" action="">
    {{ form.hidden_tag() }}

    <div class="form-group mt-3">
      <label for="email">Email</label>
      {{ form.email(class="form-control", id="email") }}
    </div>

    <div class="form-group mt-3">
      <label for="password">Password</label>
      {{ form.password(class="form-control", id="password") }}
    </div>

    {{ form.submit(class="btn btn-primary mt-3") }}
  </form>


<a href="{{ url_for('main.register') }}">Dont have an account? Sign Up</a>

</body>

</html>

{% endblock %}

app/templates/register.html
<!-- register.html -->
{% extends 'base.html' %}

{% block content %}

<h2>Register new account</h2>
<p>Enter your details below to create your ctkonnekt account.</p>

<form method="POST" action="">
    {{ form.hidden_tag() }}

    <div class="form-group mt-3">
        <label for="first_name">First Name</label>
        <input type="text" class="form-control" id="first_name" name="first_name" required>
    </div>

    <div class="form-group mt-3">
        <label for="family_name">Family Name</label>
        <input type="text" class="form-control" id="family_name" name="family_name" required>
    </div>

    <div class="form-group mt-3">
        <label for="email">Email</label>
        {{ form.email(class="form-control", id="email") }}
    </div>

    <div class="form-group mt-3">
        <label for="password">Password</label>
        {{ form.password(class="form-control", id="password") }}
    </div>

    <div class="form-group mt-3">
        <label for="confirm_password">Confirm Password</label>
        <input type="password" class="form-control" id="confirm_password" name="confirm_password" required>
    </div>

    {{ form.submit(class="btn btn-primary mt-3") }}
</form>

<a href="{{ url_for('main.login') }}">Already have an account? Login</a>

{% endblock %}

app/templates/view_post.html
<!-- view_post.html -->
{% extends 'base.html' %}

<!-- Post -->
{% block content %}

<a class="px-2" href="{{ url_for('main.view_all') }}" style="text-decoration: none;">
  <button type="button" class="btn btn-outline-primary btn-sm">
    <- Back
  </button>
</a>

<div class="post-view" data-post-id="{{ post.id }}">

  <!-- Post standard layout -->
  {% include 'partials/post_content_layout.html' %}

  <!-- Edit and delete buttons -->
  {% if current_user == post.author %}
  <div class="post-tools">
    <button class="edit-post-btn btn p-small-btn">
      <p class="px-1">Edit</p>
      <i class="fas fa-edit fa-lg"></i>
    </button>
    <button class="delete-post-btn btn p-small-btn">
      <p class="px-1">Delete</p>
      <i class="fas fa-trash-alt fa-lg"></i>
    </button>
  </div>
  {% endif %}
</div>

<!-- Edit post modal -->
<div class="modal fade" id="editPostModal" tabindex="-1" aria-labelledby="editPostModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="editPostModalLabel">Edit Post</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <!-- Edit Post Form -->
        <form id="editPostForm" action="{{ url_for('main.update_post', post_id=post.id) }}" method="post">
          <!-- Include hidden fields for CSRF and Post ID -->
          {{ edit_post_form.hidden_tag() }}
          <input type="hidden" id="editPostId" name="post_id">
          <div class="mb-3">
            {{ edit_post_form.title.label(class="form-label") }}
            <input type="text" id="editPostTitle" name="title" class="form-control">
          </div>
          <div class="mb-3">
            {{ edit_post_form.content.label(class="form-label") }}
            <textarea id="editPostContent" name="content" class="form-control"></textarea>
          </div>
          <button type="submit" class="btn btn-primary">Update Post</button>
        </form>
      </div>
    </div>
  </div>
</div>

<hr>

<!-- Comment section -->
<h3>Comments:</h3>

{% for comment in comments %}

<div class="comment" data-comment-id="{{ comment.id }}">

  <h6>{{ comment.author.first_name }} {{ comment.author.family_name }}</h6>
  <!-- Comment display area -->
  <p class="comment-content">{{ comment.content }}</p>

  <!-- Comment edit area (hidden initially) -->
  <textarea class="form-control edit-comment-content" style="display: none;">{{ comment.content }}</textarea>

  <small>{{ comment.date_posted.strftime('%Y-%m-%d %H:%M') }}</small>

  <!-- Edit and delete buttons -->
  {% if current_user == comment.author %}
  <div class="comment-tools">
    <button class="edit-btn btn c-small-btn"><i class="fas fa-edit fa-lg"></i></button>
    <button class="delete-btn btn c-small-btn"><i class="fas fa-trash-alt fa-lg"></i></button>
    <button class="save-edit-btn btn btn-dark c-small-btn" style="display: none;">Save</button>
    <button class="cancel-edit-btn btn btn-dark c-small-btn" style="display: none;">Cancel</button>
  </div>
  {% endif %}

</div>

{% endfor %}

<hr>

<h3>Add a Comment:</h3>
<form action="{{ url_for('main.add_comment', post_id=post.id) }}" method="post">
  {{ comment_form.hidden_tag() }}
  <div class="form-group">
    {{ comment_form.content.label }}
    {{ comment_form.content(rows=3, class_='form-control') }}
  </div>
  {{ comment_form.submit(class_='btn btn-primary') }}
</form>
{% endblock %}